### ISSUE TITLE
click here for recipe should open up new tab

### ISSUE THREAD

**Issue by martinliempham** [martinliempham/fork-n-spoon#25]
i looked into this and it seems more difficult than i initially thought, let me know if you have any suggestions.

**Comment by nethanelkohen** [comment]
good idea -- just implemented it. 
href tags needs target="_blank", so the code should go from this:

`a href={item.recipe.url}
`

to this:

`a href={item.recipe.url} target="_blank"
`
docs for ref:
https://www.thesitewizard.com/html-tutorial/open-links-in-new-window-or-tab.shtml
